import swaggerAutogen from 'swagger-autogen';

const doc = {
  info: {
    version: "0.8.0",
    title: "API moveis",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3000",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "Moveis",
      "description": "Endpoints"
    }
  ],
  definitions: {
    CadastrarMovel: {
      id: 2328742312,
      categoria: "Casa",
      tipo: "Madeira",
      preco: 135.00,
      descricao: "Armario 3 portas",
      fabricante: 'Tony Tornado'
    }
  }
}

const outputFile = './swagger_output.json';
const endpointsFiles = ['./src/routes/*.route.js'];

swaggerAutogen()(outputFile, endpointsFiles, doc);
